import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ReactNode } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pizza',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <main className='flex items-start justify-start flex-col mx-[67px]'>
            {children}
          </main>
      </body>
    </html>
  );
}
 